/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import clases.AnalizaLex;

/**
 *
 * @author artbast
 */
public class frmALexico extends javax.swing.JFrame {
    AnalizaLex objAnalizaLex;
    String consola[] = {"","","",""};
    int toks[] = new int[33];

    /**
     * Creates new form frmALexico
     */
    public frmALexico() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIds = new javax.swing.JTextField();
        btnVerIds = new javax.swing.JButton();
        txtEnteros = new javax.swing.JTextField();
        btnVerEnt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtReales = new javax.swing.JTextField();
        btnVerReales = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCadenas = new javax.swing.JTextField();
        btnVerCadenas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDospt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPtComa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIgual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSuma = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtResta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMult = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDiv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtComa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtParAb = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtParCer = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtLlAb = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtLlCer = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMayor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtMenor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPrLlamar = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtMayIgl = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMenIgl = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtDifer = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPrSi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtPrEntonces = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPrSino = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPrFinsi = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPrPrincipal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtVoid = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPrEnt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtPrReal = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtPrCad = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtPrSalida = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPrEntrada = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("En esta ventana se muestran el numero de tokens encontrados, asi como los errores, en el codigo fuente;");

        jLabel2.setText("IDs:");

        txtIds.setEnabled(false);
        txtIds.setFocusable(false);

        btnVerIds.setText("Ver");
        btnVerIds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerIdsActionPerformed(evt);
            }
        });

        txtEnteros.setEnabled(false);
        txtEnteros.setFocusable(false);

        btnVerEnt.setText("Ver");
        btnVerEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEntActionPerformed(evt);
            }
        });

        jLabel3.setText("Enteros:");

        txtReales.setEnabled(false);
        txtReales.setFocusable(false);

        btnVerReales.setText("Ver");
        btnVerReales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRealesActionPerformed(evt);
            }
        });

        jLabel4.setText("Reales:");

        txtCadenas.setEnabled(false);
        txtCadenas.setFocusable(false);

        btnVerCadenas.setText("Ver");
        btnVerCadenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCadenasActionPerformed(evt);
            }
        });

        jLabel5.setText("Cadenas:");

        txtDospt.setEnabled(false);
        txtDospt.setFocusable(false);

        jLabel6.setText("Dos puntos:");

        txtPtComa.setEnabled(false);
        txtPtComa.setFocusable(false);

        jLabel7.setText("Punto y coma:");

        txtIgual.setEnabled(false);
        txtIgual.setFocusable(false);

        jLabel8.setText("Igual:");

        txtSuma.setEnabled(false);
        txtSuma.setFocusable(false);

        jLabel9.setText("Suma:");

        txtResta.setEnabled(false);
        txtResta.setFocusable(false);

        jLabel10.setText("Resta:");

        txtMult.setEnabled(false);
        txtMult.setFocusable(false);

        jLabel11.setText("Multiplicacion:");

        txtDiv.setEnabled(false);
        txtDiv.setFocusable(false);

        jLabel12.setText("Division:");

        txtComa.setEnabled(false);
        txtComa.setFocusable(false);

        jLabel13.setText("Coma:");

        txtParAb.setEnabled(false);
        txtParAb.setFocusable(false);

        jLabel14.setText("Par. Abierto:");

        txtParCer.setEnabled(false);
        txtParCer.setFocusable(false);

        jLabel15.setText("Par. Cerrado:");

        txtLlAb.setEnabled(false);
        txtLlAb.setFocusable(false);

        jLabel16.setText("Llav. Abierta:");

        txtLlCer.setEnabled(false);
        txtLlCer.setFocusable(false);

        jLabel17.setText("Llav. Cerrada:");

        txtMayor.setEnabled(false);
        txtMayor.setFocusable(false);

        jLabel18.setText("Mayor que:");

        txtMenor.setEnabled(false);
        txtMenor.setFocusable(false);

        jLabel19.setText("Menor que:");

        txtPrLlamar.setEnabled(false);
        txtPrLlamar.setFocusable(false);

        jLabel20.setText("Llamar:");

        txtMayIgl.setEnabled(false);
        txtMayIgl.setFocusable(false);

        jLabel21.setText("Mayor o igual:");

        txtMenIgl.setEnabled(false);
        txtMenIgl.setFocusable(false);

        jLabel22.setText("Menor o igual:");

        txtDifer.setEnabled(false);
        txtDifer.setFocusable(false);

        jLabel23.setText("Diferente de:");

        txtPrSi.setEnabled(false);
        txtPrSi.setFocusable(false);

        jLabel24.setText("Si");

        txtPrEntonces.setEnabled(false);
        txtPrEntonces.setFocusable(false);

        jLabel25.setText("Entonces:");

        txtPrSino.setEnabled(false);
        txtPrSino.setFocusable(false);

        jLabel26.setText("Sino:");

        txtPrFinsi.setEnabled(false);
        txtPrFinsi.setFocusable(false);

        jLabel27.setText("FinSi");

        txtPrPrincipal.setEnabled(false);
        txtPrPrincipal.setFocusable(false);

        jLabel28.setText("Principal:");

        txtVoid.setEnabled(false);
        txtVoid.setFocusable(false);

        jLabel29.setText("void:");

        txtPrEnt.setEnabled(false);
        txtPrEnt.setFocusable(false);

        jLabel30.setText("entero:");

        txtPrReal.setEnabled(false);
        txtPrReal.setFocusable(false);

        jLabel31.setText("real:");

        txtPrCad.setEnabled(false);
        txtPrCad.setFocusable(false);

        jLabel32.setText("cadena:");

        txtPrSalida.setEnabled(false);
        txtPrSalida.setFocusable(false);

        jLabel33.setText("Salida");

        txtPrEntrada.setEnabled(false);
        txtPrEntrada.setFocusable(false);

        jLabel34.setText("Entrada:");

        jLabel35.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Palabras Reservadas");
        jLabel35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel36.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel36.setText("Analizador Lexico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel36)))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtCadenas, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(txtDospt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPtComa, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIgual, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSuma, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtResta, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMult, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDiv, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerCadenas))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtReales)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerReales))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIds)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerIds))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEnteros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerEnt)))))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrLlamar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDifer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtParAb, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                            .addComponent(txtParCer, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtLlAb, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtLlCer, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMayor, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMenor, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMayIgl, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMenIgl)
                                            .addComponent(txtComa))))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrEnt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(txtPrFinsi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrSino, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrEntonces, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrSi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrSalida, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrCad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrReal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtVoid))))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtIds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVerIds))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtEnteros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVerEnt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtReales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVerReales))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCadenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVerCadenas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtDospt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtPtComa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtResta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtComa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtParAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtParCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtLlAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtLlCer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtMayIgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(txtMenIgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(txtDifer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtVoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtPrEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtPrReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtPrCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtPrSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtPrEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtPrSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrEntonces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtPrSino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtPrFinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(txtPrPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtPrLlamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerIdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerIdsActionPerformed
        frmLex2 objLex2 = new frmLex2();
        objLex2.recibir(consola[0]);
        objLex2.setVisible(true);
    }//GEN-LAST:event_btnVerIdsActionPerformed

    private void btnVerEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEntActionPerformed
        frmLex2 objLex2 = new frmLex2();
        objLex2.recibir(consola[1]);
        objLex2.setVisible(true);
    }//GEN-LAST:event_btnVerEntActionPerformed

    private void btnVerRealesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRealesActionPerformed
        frmLex2 objLex2 = new frmLex2();
        objLex2.recibir(consola[2]);
        objLex2.setVisible(true);
    }//GEN-LAST:event_btnVerRealesActionPerformed

    private void btnVerCadenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCadenasActionPerformed
        frmLex2 objLex2 = new frmLex2();
        objLex2.recibir(consola[3]);
        objLex2.setVisible(true);
    }//GEN-LAST:event_btnVerCadenasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmALexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmALexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmALexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmALexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmALexico().setVisible(true);
            }
        });
    }
    
    public void analizar(String cadena){
        objAnalizaLex = new AnalizaLex(cadena);
        objAnalizaLex.encontrarTokens();
        objAnalizaLex.objLista.acToken = objAnalizaLex.objLista.prToken;
        while(objAnalizaLex.objLista.acToken != null){
            switch(objAnalizaLex.objLista.acToken.id){
                case 1: toks[0]++;
                consola[0]= consola[0] + objAnalizaLex.objLista.acToken.lex + ", ";
                break;
                case 2: toks[1]++;
                consola[1]= consola[1] + objAnalizaLex.objLista.acToken.lex + ", ";
                break;
                case 3: toks[2]++;
                consola[2]= consola[2] + objAnalizaLex.objLista.acToken.lex + ", ";
                break;
                case 4: toks[3]++;
                consola[3]= consola[3] + objAnalizaLex.objLista.acToken.lex + ", ";
                break;
                case 5: toks[4]++;
                break;
                case 6: toks[5]++;
                break;
                case 7: toks[6]++;
                break;
                case 8: toks[7]++;
                break;
                case 9: toks[8]++;
                break;
                case 10: toks[9]++;
                break;
                case 11: toks[10]++;
                break;
                case 12: toks[11]++;
                break;
                case 13: toks[12]++;
                break;
                case 14: toks[13]++;
                break;
                case 15: toks[14]++;
                break;
                case 16: toks[15]++;
                break;
                case 17: toks[16]++;
                break;
                case 18: toks[17]++;
                break;
                case 19: toks[18]++;
                break;
                case 20: toks[19]++;
                break;
                case 21: toks[20]++;
                break;
                case 22: toks[21]++;
                break;
                case 23: toks[22]++;
                break;
                case 24: toks[23]++;
                break;
                case 25: toks[24]++;
                break;
                case 26: toks[25]++;
                break;
                case 27: toks[26]++;
                break;
                case 28: toks[27]++;
                break;
                case 29: toks[28]++;
                break;
                case 30: toks[29]++;
                break;
                case 31: toks[30]++;
                break;
                case 32: toks[31]++;
                break;
                case 33: toks[32]++;
                break;
            }
            objAnalizaLex.objLista.acToken = objAnalizaLex.objLista.acToken.sig;
        }
        
        txtIds.setText(String.valueOf(toks[0]));
        txtEnteros.setText(String.valueOf(toks[1]));
        txtReales.setText(String.valueOf(toks[2]));
        txtCadenas.setText(String.valueOf(toks[3]));
        txtDospt.setText(String.valueOf(toks[4]));
        txtPtComa.setText(String.valueOf(toks[5]));
        txtIgual.setText(String.valueOf(toks[6]));
        txtSuma.setText(String.valueOf(toks[7]));
        txtResta.setText(String.valueOf(toks[8]));
        txtMult.setText(String.valueOf(toks[9]));
        txtMult.setText(String.valueOf(toks[10]));
        txtComa.setText(String.valueOf(toks[11]));
        txtParAb.setText(String.valueOf(toks[12]));
        txtParCer.setText(String.valueOf(toks[13]));
        txtLlAb.setText(String.valueOf(toks[14]));
        txtLlCer.setText(String.valueOf(toks[15]));
        txtMayor.setText(String.valueOf(toks[16]));
        txtMenor.setText(String.valueOf(toks[17]));
        txtMayIgl.setText(String.valueOf(toks[18]));
        txtMenIgl.setText(String.valueOf(toks[19]));
        txtDifer.setText(String.valueOf(toks[20]));
        txtVoid.setText(String.valueOf(toks[21]));
        txtPrEnt.setText(String.valueOf(toks[22]));
        txtPrReal.setText(String.valueOf(toks[23]));
        txtPrCad.setText(String.valueOf(toks[24]));
        txtPrSalida.setText(String.valueOf(toks[25]));
        txtPrEntrada.setText(String.valueOf(toks[26]));
        txtPrSi.setText(String.valueOf(toks[27]));
        txtPrEntonces.setText(String.valueOf(toks[28]));
        txtPrSino.setText(String.valueOf(toks[29]));
        txtPrFinsi.setText(String.valueOf(toks[30]));
        txtPrPrincipal.setText(String.valueOf(toks[31]));
        txtPrLlamar.setText(String.valueOf(toks[32]));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerCadenas;
    private javax.swing.JButton btnVerEnt;
    private javax.swing.JButton btnVerIds;
    private javax.swing.JButton btnVerReales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCadenas;
    private javax.swing.JTextField txtComa;
    private javax.swing.JTextField txtDifer;
    private javax.swing.JTextField txtDiv;
    private javax.swing.JTextField txtDospt;
    private javax.swing.JTextField txtEnteros;
    private javax.swing.JTextField txtIds;
    private javax.swing.JTextField txtIgual;
    private javax.swing.JTextField txtLlAb;
    private javax.swing.JTextField txtLlCer;
    private javax.swing.JTextField txtMayIgl;
    private javax.swing.JTextField txtMayor;
    private javax.swing.JTextField txtMenIgl;
    private javax.swing.JTextField txtMenor;
    private javax.swing.JTextField txtMult;
    private javax.swing.JTextField txtParAb;
    private javax.swing.JTextField txtParCer;
    private javax.swing.JTextField txtPrCad;
    private javax.swing.JTextField txtPrEnt;
    private javax.swing.JTextField txtPrEntonces;
    private javax.swing.JTextField txtPrEntrada;
    private javax.swing.JTextField txtPrFinsi;
    private javax.swing.JTextField txtPrLlamar;
    private javax.swing.JTextField txtPrPrincipal;
    private javax.swing.JTextField txtPrReal;
    private javax.swing.JTextField txtPrSalida;
    private javax.swing.JTextField txtPrSi;
    private javax.swing.JTextField txtPrSino;
    private javax.swing.JTextField txtPtComa;
    private javax.swing.JTextField txtReales;
    private javax.swing.JTextField txtResta;
    private javax.swing.JTextField txtSuma;
    private javax.swing.JTextField txtVoid;
    // End of variables declaration//GEN-END:variables
}
